version: "3.6"

networks:
  internal:

volumes:
  mysql:
  mongodb:

services:

  app:
    image: copypasta:dev
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
    depends_on:
      - mongo
      - mysql
    volumes:
      # For development purposes only!
      - ./view:/app/view:ro
      - ./model:/app/model:ro
      - ./controller:/app/controller:ro

  http:
    image: nginx
    networks:
      - internal
    ports:
      - 9000:80
    depends_on:
      - app
    volumes:
      - ./manifest/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./view:/app/view

  mysql:
    image: mysql:5.7
    networks:
      - internal
    environment:
       MYSQL_ROOT_PASSWORD: 1secret1
       MYSQL_DATABASE: copypasta
       MYSQL_USER: phpcontainer
       MYSQL_PASSWORD: thisIsASecretPassword
    volumes:
      - mysql:/var/lib/mysql

  mongo:
    image: mongo
    networks:
      - internal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: thisIsASecretPassword
    volumes:
      - mongodb:/data/db