version: "3.6"

networks:
  internal:

volumes:
  mysql:
  mongodb:

services:

  app:
    image: copypasta:dev
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
    depends_on:
      - mongo
      - mysql

  http:
    image: nginx
    networks:
      - internal
    ports:
      - 8000:80
    depends_on:
      - app
    volumes:
      - ./manifest/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./view:/app/view

  mysql:
    image: mysql:5.7
    networks:
      - internal
    ports:
     - 10:3306
    environment:
       MYSQL_ROOT_PASSWORD: 1secret1
       MYSQL_DATABASE: copypasta
       MYSQL_USER: phpcontainer
       MYSQL_PASSWORD: thisIsASecretPassword
    volumes:
      - mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro

  mongo:
    image: mongo
    networks:
      - internal
    environment:
      MONGO_INITDB_DATABASE: copypasta
    volumes:
      - mongodb:/data/db